(require 'org)

(defun js3r-ternary-to-if ()
  (interactive)
  (js3r--guard)
  (save-excursion
    (let* ((ternary (js3r--closest 'js3-cond-node-p))
           (test-expr (js3-node-string (js3-cond-node-test-expr ternary)))
           (true-expr (js3-node-string (js3-cond-node-true-expr ternary)))
           (false-expr (js3-node-string (js3-cond-node-false-expr ternary)))
           (stmt (js3-node-parent-stmt ternary))
           (stmt-pre (buffer-substring (js3-node-abs-pos stmt) (js3-node-abs-pos ternary)))
           (stmt-post (org-trim (buffer-substring (js3-node-abs-end ternary) (js3-node-abs-end stmt))))
           (beg (js3-node-abs-pos stmt)))
      (goto-char beg)
      (delete-char (js3-node-len stmt))
      (insert "if (" test-expr ") {")
      (newline)
      (insert stmt-pre true-expr stmt-post)
      (newline)
      (insert "} else {")
      (newline)
      (insert stmt-pre false-expr stmt-post)
      (newline)
      (insert "}")
      (indent-region beg (point)))))

(provide 'js3r-conditionals)
